---
title: "Cash Grab Arena -- Playtest Data Analysis"
author: "Version 0.13.*"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# Load in relevant packages
library(ggplot2)
library(glue)
library(purrr)
library(tidyverse)
library(ggforce)

#Write functions to append the data more efficiently.
read_in_data <- function(fileName, playtestDate = "99/99/9999", playtestVersion = "0.0.*", hasHeaders = FALSE) {
  out <- read.csv(fileName, hasHeaders)
  colnames(out) <- c("Class", "Entries", "Coins", "Kills", "Deaths", "Vigor.Flask.Entries", 
            "Bandage.Entries", "Accelerator.Entries", "Echo.Bolt.Entries",
            "Spring.Plume.Entries", "Hedge.Seed.Entries", "Risk.It.Biscuit.Entries",
            "Nox.Bomb.Entries", "Flame.Trap.Entries", "Lava.Cake.Entries", 
            "Smoke.Screen.Entries",
            "Vigor.Flask.Coins", "Bandage.Coins", "Accelerator.Coins", 
            "Echo.Bolt.Coins", "Spring.Plume.Coins", "Hedge.Seed.Coins",
            "Risk.It.Biscuit.Coins", "Nox.Bomb.Coins", "Flame.Trap.Coins", 
            "Lava.Cake.Coins", "Smoke.Screen.Coins")
  out <- out |>
    mutate(Date = playtestDate,
           Version = playtestVersion)
  return(out)
}

merge_playtests <- function(dataframes) {
  out <- dataframes[[1]]
  
  for (i in 2:length(dataframes)) {
    suppressMessages(
      out <- out |>
      full_join(dataframes[[i]])
    )
  }
  
  return(out)
}
```

```{r echo=FALSE}
#Column names to fit to each dataset
varnames <- c("Class", "Entries", "Coins", "Kills", "Deaths", "Vigor.Flask.Entries", 
            "Bandage.Entries", "Accelerator.Entries", "Echo.Bolt.Entries",
            "Spring.Plume.Entries", "Hedge.Seed.Entries", "Risk.It.Biscuit.Entries",
            "Nox.Bomb.Entries", "Flame.Trap.Entries", "Lava.Cake.Entries", 
            "Smoke.Screen.Entries",
            "Vigor.Flask.Coins", "Bandage.Coins", "Accelerator.Coins", 
            "Echo.Bolt.Coins", "Spring.Plume.Coins", "Hedge.Seed.Coins",
            "Risk.It.Biscuit.Coins", "Nox.Bomb.Coins", "Flame.Trap.Coins", 
            "Lava.Cake.Coins", "Smoke.Screen.Coins"
            )

# Read in data
setwd("data_old")
march16 <- read_in_data("March 16 2025.csv", "03/16/2025", "0.12.*", TRUE)
march22 <- read_in_data("March 22 2025.csv", "03/22/2025", "0.12.*", TRUE)
march30 <- read_in_data("March 30 2025.csv", "03/30/2025", "0.12.*")
april27 <- read_in_data("April 27 2025.csv", "04/27/2025", "0.12.*")
may11 <- read_in_data("May 11 2025.csv", "05/11/2025", "0.12.*")
june26 <- read_in_data("June 26 2025.csv", "06/26/2025", "0.12.*")
july6 <- read_in_data("July 6 2025.csv", "07/06/2025", "0.12.*")
july27 <- read_in_data("July 27 2025.csv", "07/27/2025", "0.12.*")
august31 <- read_in_data("August 31 2025.csv", "08/31/2025", "0.12.*")
september21 <- read_in_data("September 21 2025.csv", "04/27/2025", "0.13.*")


#Merge obs. into one set of data
dflist <- list(march16, march22, march30, april27, may11, june26, july6, july27, august31, september21)
cgada <- merge_playtests(dflist)

#Perform computations necessary for outputs
cgada <- cgada |>
  filter(Version == "0.13.*") |>
  mutate(Entries.Total = sum(Entries), 
         KPE = Kills / Entries,
         CPE = Coins / Entries,
         KPE.scaled = (KPE - (0.8 * min(KPE))) / ((1.2 * max(KPE)) - (0.8 * min(KPE))),
         CPE.scaled = (CPE - (0.8 * min(CPE))) / ((1.2 * max(CPE)) - (0.8 * min(CPE))),
         Rel.Eff = KPE.scaled - CPE.scaled) |>
  group_by(Class) |>
  mutate(Entry.Percent = Entries / Entries.Total,
         KPE.mean = mean(KPE, na.rm = TRUE),
         KPE.sd = sd(KPE, na.rm = TRUE),
         CPE.mean = mean(CPE, na.rm = TRUE),
         CPE.sd = sd(CPE, na.rm = TRUE),
         Rel.Eff.mean = mean(Rel.Eff, na.rm = TRUE),
         Rel.Eff.sd = sd(Rel.Eff, na.rm = TRUE))
```

# Class Data

## General Class Popularity

```{r echo=FALSE}
#Std. Dev
EP.sigma <- sd(cgada$Entry.Percent)

ggplot(cgada, aes(x = Class, y = Entry.Percent)) +
  geom_bar(stat = "identity", color = "black", fill = "green") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("% of Total Lives") +
  labs(title = "Class Popularity (% of Total Lives Played)",
       caption = glue("Std. Dev.: {round(EP.sigma, 3)}
                      Red line indicates expected popularity assuming classes are to be equally used.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_hline(yintercept = 1 / nrow(distinct(cgada, Class)), color = "red")
```

## Kills Per Entry

```{r echo=FALSE}
ggplot(cgada, aes(x = Class, y = KPE)) +
  geom_bar(stat = "summary", fun = "mean", color = "black", fill = "slateblue") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("Kills") + ylim(0, max(cgada$KPE)) +
  labs(title = "Kills per Entry (within-Class Variance)",
       caption = glue("Red line indicates average across all classes.
                      Error bars indicate values which we could likely observe on repeated playtests, given current balancing.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(ymin = cgada$KPE.mean - cgada$KPE.sd,
                ymax = cgada$KPE.mean + cgada$KPE.sd,
                width = 0.5) +
  geom_hline(yintercept = mean(cgada$KPE, na.rm = TRUE), color = "red")
```

## Coins Per Entry

```{r echo=FALSE}
ggplot(cgada, aes(x = Class, y = CPE)) +
  geom_bar(stat = "summary", fun = "mean", color = "black", fill = "gold") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("Coins") + ylim(0, max(cgada$CPE)) +
  labs(title = "Average Coins per Entry (within-Class Variance)",
       caption = glue("Red line indicates average across all classes.
                      Error bars indicate values which we could likely observe on repeated playtests, given current balancing.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(ymin = cgada$CPE.mean - cgada$CPE.sd,
                ymax = cgada$CPE.mean + cgada$CPE.sd,
                width = 0.5) +
  geom_hline(yintercept = mean(cgada$CPE, na.rm = TRUE), color = "red")
```

## Relative Efficiency

```{r echo=FALSE}
ggplot(cgada, aes(x = Class, y = Rel.Eff)) +
  geom_bar(stat = "identity", color = "black", fill = "red") +
  theme(legend.position = "none") +
  xlab("Class") + ylab("% Difference") +
  labs(title = "Relative Efficiency",
          subtitle = "Difference in scaled Kills per Entry and Coins per Entry",
          caption = glue("Positive values indicate more efficient kill generation per life.
          Negative values indicate more efficient coin earnings per life.
          Larger magnitudes suggest more extreme specializations.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_errorbar(ymin = cgada$Rel.Eff.mean - cgada$Rel.Eff.sd,
                ymax = cgada$Rel.Eff.mean + cgada$Rel.Eff.sd,
                width = 0.5) +
  geom_hline(yintercept = 0, color = "black")
```

# Trinket Data

```{r results=FALSE, echo=FALSE}
Class <- distinct(cgada, Class)$Class
Trinket <- c("Vigor Flask", "Bandage", "Accelerator", "Echo Bolt", "Spring Plume", "Hedge Seed", "Risk-it-Biscuit", "Nox Bomb", "Flame Trap", "Lava Cake", "Smoke Screen")
trinket.entries <- cgada[,c(6:16)]
trinket.coins <- cgada[,c(17:27)]

trinket.pop <- rep(NA, ncol(trinket.entries))
trinket.CPE <- rep(NA, ncol(trinket.coins))

#Sum up the values of each trinket and save to vectors
for (i in 1:ncol(trinket.entries)) {
  trinket.pop[i] <- sum(trinket.entries[,i])
  trinket.CPE[i] <- sum(trinket.coins[,i]) / trinket.pop[i]
}
tp <- trinket.pop / sum(cgada$Entries)
trinket.data <- data.frame(Trinket, trinket.pop, trinket.CPE, tp)

#Create the Class-and-Trinket ranking

grouped.trinket.entries <- cgada |>
  group_by(Class) |>
  summarise(vfsum = sum(Vigor.Flask.Entries),
            bsum = sum(Bandage.Entries),
            asum = sum(Accelerator.Entries),
            ebsum = sum(Echo.Bolt.Entries),
            spsum = sum(Spring.Plume.Entries),
            hssum = sum(Hedge.Seed.Entries),
            ribsum = sum(Risk.It.Biscuit.Entries),
            nbsum = sum(Nox.Bomb.Entries),
            ftsum = sum(Flame.Trap.Entries),
            lcsum = sum(Lava.Cake.Entries),
            sssum = sum(Smoke.Screen.Entries))

grouped.trinket.entries <- grouped.trinket.entries[,c(2:12)]

ct.string <- rep(NA, length(Class) * ncol(trinket.entries))
ct.count <- rep(NA, length(Class) * ncol(trinket.entries))
for (i in 1:length(Class)) {
  for (j in 1:ncol(trinket.entries)) {
    ct.string[(11 * i) - (11 - j)] <- glue("{Class[i]}/{Trinket[j]}")
    ct.count[(11 * i) - (11 - j)] <- grouped.trinket.entries[i,j]
  }
}
ct.count <- unlist(ct.count)
ct.rank <- data.frame(ct.string, ct.count)
ct.rank.sorted <- ct.rank[order(-ct.count),]
```

## Trinket Popularity

```{r echo=FALSE}
tp.sigma <- sd(trinket.data$tp)

ggplot(trinket.data, aes(x = Trinket, y = tp)) +
  geom_bar(stat = "identity", color = "black", fill = "orange") +
  theme(legend.position = "none") +
  xlab("Trinket") + ylab("% Entries") +
  labs(title = "Trinket Usage (% of Total Lives Played)",
  caption = glue("Std. Dev.: {round(tp.sigma, 3)}
                 Red line indicates expected usage for each trinket, assuming they are to be equally used.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_hline(yintercept = 1 / nrow(trinket.data), color = "red")
```

## Trinket Efficacy

```{r echo=FALSE}
tc.sigma <- sd(trinket.data$trinket.CPE)

ggplot(trinket.data, aes(x = Trinket, y = trinket.CPE)) +
  geom_bar(stat = "identity", color = "black", fill = "gold3") +
  theme(legend.position = "none") +
  xlab("Trinket") + ylab("Coins") +
  labs(title = "Trinket Efficacy (Coins per Life Played)",
  caption = glue("Std. Dev.: {round(tc.sigma, 3)}
                 Red line indicates average across all trinkets.")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_hline(yintercept = mean(trinket.data$trinket.CPE), color = "red")
```

## Top Class-and-Trinket Combos by Lives Played

```{r echo=FALSE}
colnames(ct.rank.sorted) <- c("Combo", "Lives Played")
Rank <- rep(1:nrow(ct.rank.sorted))
ct.rank.sorted <- cbind(Rank, ct.rank.sorted)
print(ct.rank.sorted[c(1:20),], row.names = FALSE)
```

## [Click here to return to the main page.](https://maxstca.github.io/cgada/)